#!/bin/bash
if [ $# -eq 0 ]; then
        echo "Please add a name for the new zone" >&2
        exit 1
fi

if [ "$(id -u)" -ne 0 ]; then
        echo "Please run as root" >&2
        exit 1
fi

echo -e "\n" >> /etc/bind/named.conf.mrt-zones
echo -e	"zone \"$1.seppe-lenaerts.sb.uclllabs.be\" {
		type master;
		file \"/etc/bind/mrt-tests/db.$1\";
		allow-transfer { 193.191.177.207; };
	};" >> /etc/bind/named.conf.mrt-zones


echo 	"\$TTL    1
	\$ORIGIN $1.seppe-lenaerts.sb.uclllabs.be.
	@       IN      SOA     ns.$1.seppe-lenaerts.sb.uclllabs.be. root.$1.seppe-lenaerts.sb.uclllabs.be. (
		2	; Serial
		5M	; Refresh
		5M	; Retry
		5M	; Expire
		5M )	; Negative Cache TTL" >> /etc/bind/mrt-tests/db.$1

echo "@       IN      NS      ns.seppe-lenaerts.sb.uclllabs.be." >> /etc/bind/mrt-tests/db.$1
echo "@       IN      A       193.191.177.207" >> /etc/bind/mrt-tests/db.$1
echo "ns      IN      A       193.191.177.207" >> /etc/bind/mrt-tests/db.$1

echo "$1     IN      NS      ns.seppe-lenaerts.sb.uclllabs.be." >> /etc/bind/db.local

SERIAL=$(grep -Po '\d+(?=\s+; Serial)' /etc/bind/db.local)
NEW_SERIAL=$(("$SERIAL" + 1))
sed -i "0,/$SERIAL/s//$NEW_SERIAL/" /etc/bind/db.local


systemctl restart bind9
